### ISSUE TITLE
sbt update always fail on this project

### ISSUE THREAD

**Issue by epiphyllum** [scalaz/scalaz#1360]
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-native#sbt-crossproject;0.1.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.scala-native:sbt-crossproject:0.1.0 (scalaVersion=2.10, sbtVersion=0.13)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scala-native:sbt-crossproject:0.1.0 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		  +- org.scala-native:sbt-scala-native:0.1.0 (scalaVersion=2.10, sbtVersion=0.13) (/Users/hary/workspace/scala/scalaz/project/plugins.sbt#L5-6)
[warn] 		  +- default:scalaz-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: org.scala-native#sbt-crossproject;0.1.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
```

**Comment by xuwei-k** [comment]
Maybe https://twitter.com/scala_sbt/status/854050606058799104 ?

**Comment by S11001001** [comment]
Confirmed `update` succeeds.
