### ISSUE TITLE
Heap#toList StackOverflow

### ISSUE THREAD

**Issue by xuwei-k** [scalaz/scalaz#240]
```
$ screpl org.scalaz%%scalaz-core%7.0.0-M7
[info] Set current project to default-cc9485 (in build file:/Users/user/.conscript/boot/ivy-console/)
Welcome to Scala version 2.9.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_09).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import scalaz._,Scalaz._
import scalaz._
import Scalaz._

scala> Heap.fromData(1 to 10000 toList).toList
java.lang.StackOverflowError
        at scalaz.TreeFunctions$$anon$3.<init>(Tree.scala:138)
        at scalaz.TreeFunctions$class.node(Tree.scala:138)
        at scalaz.Tree$.node(Tree.scala:102)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:140)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
        at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:181)
```

**Comment by vmarquez** [comment]
This is fixed in my branch.

**Comment by vmarquez** [comment]
Any update on this @xuwei-k ?  Let me know if you want me to do a different fix or to close my PR.
