### ISSUE TITLE
Cord append causing StackOverflow

### ISSUE THREAD

**Issue by japgolly** [scalaz/scalaz#497]
Hi!
I have a few levels of methods returning Cords, calling each other, and appending results directly using `++` into a larger, master Cord. When testing with ScalaCheck it often StackOverflows.

Stack trace:

```
at scalaz.FingerTree$$anonfun$addDigits2$1$$anonfun$apply$251.<init>(FingerTree.scala:551)
at scalaz.FingerTree$$anonfun$addDigits2$1.apply(FingerTree.scala:551)
at scalaz.FingerTree$$anonfun$addDigits2$1.apply(FingerTree.scala:551)
at scalaz.FingerTree$$anonfun$add2$1.apply(FingerTree.scala:458)
at scalaz.FingerTree$$anonfun$add2$1.apply(FingerTree.scala:458)
at scalaz.FingerTreeFunctions$$anon$5.fold(FingerTree.scala:936)
at scalaz.FingerTree.add2(FingerTree.scala:457)
at scalaz.FingerTree.addDigits2(FingerTree.scala:551)
at scalaz.FingerTree$$anonfun$add2$3$$anonfun$apply$64$$anonfun$apply$65.apply(FingerTree.scala:465)
at scalaz.FingerTree$$anonfun$add2$3$$anonfun$apply$64$$anonfun$apply$65.apply(FingerTree.scala:465)
at scalaz.FingerTreeFunctions$$anon$20.scalaz$FingerTreeFunctions$$anon$$mz$lzycompute(FingerTree.scala:954)
at scalaz.FingerTreeFunctions$$anon$20.scalaz$FingerTreeFunctions$$anon$$mz(FingerTree.scala:954)
at scalaz.FingerTreeFunctions$$anon$20$$anonfun$fold$1.apply(FingerTree.scala:956)
at scalaz.FingerTreeFunctions$$anon$20$$anonfun$fold$1.apply(FingerTree.scala:956)
at scalaz.FingerTree$$anonfun$add2$1.apply(FingerTree.scala:458)
at scalaz.FingerTree$$anonfun$add2$1.apply(FingerTree.scala:458)
at scalaz.FingerTreeFunctions$$anon$5.fold(FingerTree.scala:936)
at scalaz.FingerTree.add2(FingerTree.scala:457)
at scalaz.FingerTree.addDigits2(FingerTree.scala:551)
...
```

The stack trace differs here but a SO is still producable via:

```
Stream.continually(Cord(".")) take 32000 concatenate
```

Using 7.0.3.

**Comment by TomasMikula** [comment]
I am lazy to track down where exactly this was fixed, but the mentioned expression

```scala
Stream.continually(Cord(".")) take 32000 concatenate
```

does not overflow the stack anymore.
