### ISSUE TITLE
Heap is not stack safe

### ISSUE THREAD

**Issue by julien-truffaut** [scalaz/scalaz#911]
```scala
val as = (1 to 10000).toList
val q = as.foldLeft(Heap.Empty[Int])(_.+(_))
q.toStream.toList ==== as.sorted
```

causes

```
null
java.lang.StackOverflowError
	at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:196)
	at scalaz.TreeFunctions$$anon$3.subForest$lzycompute(Tree.scala:153)
	at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:153)
	at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:196)
	at scalaz.Heap$$anonfun$insertWith$2$$anonfun$apply$12.apply(Heap.scala:196)
	at scalaz.TreeFunctions$$anon$3.subForest$lzycompute(Tree.scala:153)
	at scalaz.TreeFunctions$$anon$3.subForest(Tree.scala:153)
```

**Comment by xuwei-k** [comment]
duplicate? https://github.com/scalaz/scalaz/issues/240

**Comment by julien-truffaut** [comment]
@xuwei-k it seems so, closing it
